 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <parent>
    <groupId>org.opengis.cite</groupId>
    <artifactId>ets-common</artifactId>
    <version>15-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>ets-kml2</artifactId>
  <version>0.6-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>OGC KML 2.x Conformance Test Suite</name>
  <description>Verifies that a KML 2.x resource conforms to the relevant OGC 
  specification (OGC 12-007r2, OGC 07-147r2).</description>
  <url>http://opengeospatial.github.io/ets-kml2/</url>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://opensource.org/licenses/Apache-2.0</url>
    </license>
  </licenses>

  <organization>
    <name>Open Geospatial Consortium</name>
    <url>http://www.opengeospatial.org/</url>
  </organization>
  <scm>
    <connection>scm:git:https://github.com/opengeospatial/ets-kml2.git</connection>
    <developerConnection>scm:git:git@github.com:opengeospatial/ets-kml2.git</developerConnection>
    <url>https://github.com/opengeospatial/ets-kml2</url>
    <tag>HEAD</tag>
  </scm>
  <issueManagement>
    <system>GitHub Issue Tracker</system>
    <url>https://github.com/opengeospatial/ets-kml2/issues</url>
  </issueManagement>
  <developers>
    <developer>
      <name>R. Martell</name>
      <url>https://github.com/rjmartell</url>
      <timezone>Canada/Pacific</timezone>
    </developer>
  </developers>

  <properties>
    <ets-code>kml2</ets-code>
    <spec-version>2.x</spec-version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.opengis.cite.xerces</groupId>
      <artifactId>xercesImpl-xsd11-shaded</artifactId>
      <version>2.12-beta-r1667115</version>
      <exclusions>
      	<exclusion>
      		<groupId>xml-apis</groupId>
      		<artifactId>xml-apis</artifactId>
      	</exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.opengis.cite</groupId>
      <artifactId>schema-utils</artifactId>
      <exclusions>
        <exclusion>
          <groupId>xerces</groupId>
          <artifactId>xercesImpl</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>edu.princeton.cup</groupId>
      <artifactId>java-cup</artifactId>
      <version>10k</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.locationtech.jts</groupId>
      <artifactId>jts-core</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opengis.cite.teamengine</groupId>
      <artifactId>teamengine-spi</artifactId>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.jena</groupId>
      <artifactId>jena-iri</artifactId>
    </dependency>
    <dependency>
      <groupId>com.beust</groupId>
      <artifactId>jcommander</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opengis.cite.saxon</groupId>
      <artifactId>saxon9</artifactId>
    </dependency>
    <dependency>
      <groupId>xerces</groupId>
      <artifactId>xercesImpl</artifactId>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jersey.connectors</groupId>
      <artifactId>jersey-apache-connector</artifactId>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <archive>
            <manifest>
              <mainClass>org.opengis.cite.kml2.TestNGController</mainClass>
            </manifest>
          </archive>
          <descriptors>
            <descriptor>${basedir}/src/assembly/deps.xml</descriptor>
            <descriptor>${basedir}/src/assembly/ctl-scripts.xml</descriptor>
            <descriptor>${basedir}/src/assembly/aio.xml</descriptor>
          </descriptors>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-site-plugin</artifactId>
      </plugin>
    </plugins>
  </build>  
</project>
